syntax = "proto3";

package proto;

option go_package = "MintDb/proto";

service MintDb {
  rpc Get (GetRequest) returns (GetResponse) {}
  rpc Set (SetRequest) returns (SetResponse) {}
  rpc Delete(DeleteRequest) returns (DeleteResponse) {}
}

message GetRequest {
  string key = 1;
}

message GetResponse {
  string value = 1;
  optional string error = 2;
}

message SetRequest {
  string key = 1;
  string value = 2;
}

message SetResponse {
  bool result = 1;
  optional string error = 2;
}

message DeleteRequest {
  string key = 1;
}

message DeleteResponse {
  bool result = 1;
  optional string error = 2;
}
